baseURL = "https://nav.wildwolf.tech/"
languageCode = "zh-CN"
title = "野狼博客导航"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""

![](https://wiki-media-1253965369.cos.ap-guangzhou.myqcloud.com/img/20210724155549.png)